export const STATES = {
  WELCOME: "WELCOME",
  GAME: "GAME",
  RULE: "RULE",
  EASY_CARD_NUM: 27,
  NOT_EASY_CARD_NUM: 81,
  START_CARDS_NUM: 12,
  BORDER_SELECTED: "4px solid #262626",
  BORDER_SET: "4px solid #00B74A",
  BORDER_NOTSET: "4px solid #F93154",
};